[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pylib2mcp"
version = "1.0.0"
description = "Port Python library functions as MCP tools"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "fastmcp==2.8.1",
    "pydantic>=2.11.7",
    "typer>=0.16.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
]

[tool.black]
line-length = 500