name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build pylib2mcp
        run: |
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Test
        run: |
          source .venv/bin/activate
          tox